CREATE TABLE "IDBS_ADMIN"."DECLARATION"(ID NUMBER,
DECL_MOTOR_ID NUMBER, 
DRVFILE_NAME VARCHAR2(100 BYTE), 
DRVUPLOAD_DATE VARCHAR2(100 BYTE))
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDBS_DATA" ;
  
  
  

  CREATE SEQUENCE declaration_pk_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;